<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galeri extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Galeri_model');
        
    }

    function index()
    {
    	$data['galeri'] = $this->Galeri_model->get_all_galeri();

        $data['_view'] = 'layouts/front/galeri';
        $this->load->view('layouts/front/main',$data);
    }
}
