<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konfirmasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
         $this->load->model('Pemesanan_model');
          $this->load->model('Konfirmasi_t_model');
         $this->load->model('Pemesanan_tourguide_model');
         $this->load->model('Konfirmasi_p_model');
    }

    function index()
    {
    	// $data['konfirmasi_pemesananpaket'] = $this->Pemesanan_model->get_all_pemesanan();
        $data['_view'] = 'layouts/front/konfirmasi';
        $this->load->view('layouts/front/main',$data);
    }

    function add()
    {   

        

        if(isset($_POST) && count($_POST) > 0)     
        {   
            // die($this->input->post('pembayaran'));
            $cek = $this->input->post('pembayaran');
            $tgl =  date('Y-m-d');

            if($cek == 'paket'){

                $params ['tgl_sekarang'] = $tgl;
                $params ['invoice'] = $this->input->post('invoice');
                // $params ['nama'] = $this->input->post('nama');
                // $params ['jumlah'] = $this->input->post('jumlah');
                $params ['gambar'] = $this->input->post('gambar');
                // $params ['tgl_kirim'] = $this->input->post('tgl_kirim');
              
                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params['gambar'] = $foto_name;
                }

                $invoice = $this->input->post('invoice');
                $cekinvoice = $this->Pemesanan_model->cek_invoice($invoice);
                

                if(count($cekinvoice) >= 1){

                    // $data_pemesanan['status'] = 1;
                    // $pemesanan = $this->Pemesanan_model->update_pemesanan($cekinvoice->id_pemesanan,$data_pemesanan);

                    $konfirmasi_p_id = $this->Konfirmasi_p_model->add_konfirmasi_p($params);
                    redirect('validasi_paket');
                } else {
                    // die("invoice yang dimasukkan salah");
                echo '<script type="text/javascript">alert("Invoice tidak cocok, masukkan invoice lagi");window.location.replace("'.base_url('Konfirmasi').'")</script>';
                // redirect('Konfirmasi');
                    }
            } else {
                $params ['tgl_sekarang'] = $tgl;
                $params ['invoice'] = $this->input->post('invoice');
                // $params ['nama'] = $this->input->post('nama');
                // $params ['jumlah'] = $this->input->post('jumlah');
                // $params ['tgl_kirim'] = $this->input->post('tgl_kirim'); 
                if (!empty($_FILES['gambar']['name'])) {
                    // die("tes");
                    $foto_name    = $this->upload_foto();
                    $params['gambar'] = $foto_name;
                    }
                

                $invoice = $this->input->post('invoice');
                $cekinvoice = $this->Pemesanan_tourguide_model->cek_invoice($invoice);
                

                if(count($cekinvoice) >= 1){
                    $konfirmasi_t_id = $this->Konfirmasi_t_model->add_konfirmasi_t($params);
                } else {
                    redirect('Konfirmasi');
                }
                
                redirect('validasi_paket');
            }

            
        }
        else
        {            
            $data['_view'] = 'layouts/front/validasi_paket';
            $this->load->view('layouts/main',$data);
        }
    }  

    function upload_foto(){
        $set_name   = "buktitransfer-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/bukti_pembayaran/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }
}
