<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konfirmasi_paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
         $this->load->model('Pemesanan_model');
         $this->load->model('Konfirmasi_p_model');
    }

    function index()
    {
    	// $data['konfirmasi_pemesananpaket'] = $this->Pemesanan_model->get_all_pemesanan();
        $data['_view'] = 'layouts/front/konfirmasi_paket';
        $this->load->view('layouts/front/main',$data);
    }

    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            
            $tgl =  date('Y-m-d');

                $params ['tgl_sekarang'] = $tgl;
                $params ['invoice'] = $this->input->post('invoice');
                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params['gambar'] = $foto_name;
                }

                $invoice = $this->input->post('invoice');
                $cekinvoice = $this->Pemesanan_model->cek_invoice($invoice);
                

                if(count($cekinvoice) >= 1){

                    $data_pemesanan['status'] = 1;
                    $pemesanan = $this->Pemesanan_model->update_pemesanan($cekinvoice->id_pemesanan,$data_pemesanan);

                    $konfirmasi_p_id = $this->Konfirmasi_p_model->add_konfirmasi_p($params);
                    redirect('validasi_paket');
                }else {
                redirect('Konfirmasi_paket');
                    }
        }
        else
        {            
            $data['_view'] = 'layouts/front/konfirmasi_paket';
            $this->load->view('layouts/front/main',$data);
        }
    }  
    // function add()
    // {   

        

    //     if(isset($_POST) && count($_POST) > 0)     
    //     {   
    //         $tgl =  date('Y-m-d');

    //             $params ['tgl_sekarang'] = $tgl;
    //             $params ['invoice'] = $this->input->post('invoice');
    //             if (!empty($_FILES['gambar']['name'])) {
    //                 $foto_name    = $this->upload_foto();
    //                 $params['gambar'] = $foto_name;
    //             }

    //             $invoice = $this->input->post('invoice');
    //             $cekinvoice = $this->Pemesanan_model->cek_invoice($invoice);
                

    //             if(count($cekinvoice) >= 1){

    //                 $data_pemesanan['status'] = 1;
    //                 $pemesanan = $this->Pemesanan_model->update_pemesanan($cekinvoice->id_pemesanan,$data_pemesanan);

    //                 $konfirmasi_p_id = $this->Konfirmasi_p_model->add_konfirmasi_p($params);
    //                 redirect('validasi_paket');
    //             } else {
    //                 // die("invoice yang dimasukkan salah");
                
    //             redirect('Konfirmasi_paket');
    //                 }
        
    //         $data['_view'] = 'layouts/front/validasi_paket';
    //         $this->load->view('layouts/main',$data);
    //     }
    // }  

    function upload_foto(){
        $set_name   = "buktitransfer-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/bukti_pembayaran/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }
}
