<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paket_wisata extends CI_Controller{
    function __construct()
    {
        parent::__construct();
         $this->load->model('Paket_wisatum_model');
    }

    function index($offset=0)
    {
        $paket_wisata = $this->db->get("paket_wisata");


        $config['total_rows']=$paket_wisata->num_rows();
        $config['base_url']= base_url().'Paket_wisata/index';
        $config['per_page']= 20;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Paket_wisatum_model->ambil_data($config['per_page'], $offset);

    	$data['paket_wisata'] = $this->Paket_wisatum_model->get_all_paket_wisata();
        $data['_view'] = 'layouts/front/paket_wisata';
        $this->load->view('layouts/front/main',$data);
    }

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['paket_wisata'] = $this->Paket_wisatum_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/front/caripaketwisata';
    $this->load->view('layouts/front/main', $data); //menampilkan data yang sudah dicari
    }
}
