<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pembayaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        // $this->load->model('Paket_wisatum_model');
    }

    function index()
    {
    	
        $data['_view'] = 'layouts/front/pembayaran';
        $this->load->view('layouts/front/main',$data);
    }
}
