<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Restaurant extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant_model');
    }

    function index($offset=0)
    {

        $restaurant = $this->db->get("restaurant");


        $config['total_rows']=$restaurant->num_rows();
        $config['base_url']= base_url().'Restaurant/index';
        $config['per_page']= 6;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Restaurant_model->ambil_data($config['per_page'], $offset);

        $data['restaurant'] = $this->Restaurant_model->get_all_restaurant();
    	
        $data['_view'] = 'layouts/front/restaurant';
        $this->load->view('layouts/front/main',$data);
    }

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['restaurant'] = $this->Restaurant_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/front/carirestaurant';
    $this->load->view('layouts/front/main', $data); //menampilkan data yang sudah dicari
    }
}
