<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pemesanan_model');
        $this->load->model('Sk_model');
        $this->load->library('email');
    }

    function index()
    {
        $data['_view'] = 'layouts/front/sk';
        $this->load->view('layouts/front/main',$data);
    }

    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
              'nama' => $this->input->post('nama'),
              'nilai' => $this->input->post('nilai'),
              'sk' => $this->input->post('sk'),       
            );

           
                  $sk_id = $this->Sk_model->add_sk($params);
                  redirect('Sk/terkirim');
                
        }
        else
        {            
            $data['_view'] = 'layouts/front/bookingpaket_proses';
            $this->load->view('layouts/main',$data);
        }

         
    }

    function terkirim()
    {
      $data['_view'] = 'layouts/front/skterkirim';
        $this->load->view('layouts/front/main',$data);
    }

  
    

    
}
