<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tourguide extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tour_guide_model');
        $this->load->model('Pemesanan_tourguide_model');
    }

    function index($offset=0)
    {
        $tour_guide = $this->db->get("tour_guide");


        $config['total_rows']=$tour_guide->num_rows();
        $config['base_url']= base_url().'Tourguide/index';
        $config['per_page']= 20;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Tour_guide_model->ambil_data($config['per_page'], $offset);

        $data['tour_guide'] = $this->Tour_guide_model->get_all_tour_guide();
    	// $data['tour_guide'] = $this->Tour_guide_model->get_where_tour_guide();
        // $data['tour_guide'] = $this->Tour_guide_model->get_where_tour_guid();
        $data['_view'] = 'layouts/front/tour_guide';
        $this->load->view('layouts/front/main',$data);
    }

     function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['tour_guide'] = $this->Tour_guide_model->cariguide($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/front/caritourguide';
    $this->load->view('layouts/front/main', $data); //menampilkan data yang sudah dicari
    }
}
