<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galeri_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get galeri by id_galeri
     */
    function get_galeri($id_galeri)
    {
        return $this->db->get_where('galeri',array('id_galeri'=>$id_galeri))->row();
    }
        
    /*
     * Get all galeri
     */
    function get_all_galeri()
    {
        $this->db->order_by('id_galeri', 'desc');
        return $this->db->get('galeri')->result_array();
    }
        
    /*
     * function to add new galeri
     */
    function add_galeri($params)
    {
        $this->db->insert('galeri',$params);
        return $this->db->insert_id();
    }


    
    // Fungsi untuk melakukan proses upload file
    function upload(){
        $config['upload_path'] = 'resources/upload/';
        $config['allowed_types'] = 'jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['remove_space'] = TRUE;
    
        $this->load->library('upload', $config); // Load konfigurasi uploadnya
        if($this->upload->do_upload('gambar')){ // Lakukan upload dan Cek jika proses upload berhasil
            // Jika berhasil :
            $return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
            return $return;
        }else{
            // Jika gagal :
            $return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
            return $return;
        }
    }
    
    // Fungsi untuk menyimpan data ke database
    function save($upload){
        $data = array(
            // 'deskripsi'=>$this->input->post('input_deskripsi'),
            'gambar' => $upload['gambar']['file_name']
            // 'ukuran_file' => $upload['file']['file_size'],
            // 'tipe_file' => $upload['file']['file_type']
        );
        
        $this->db->insert('galeri', $data);
    }


    
    /*
     * function to update galeri
     */
    function update_galeri($id_galeri,$params)
    {
        $this->db->where('id_galeri',$id_galeri);
        return $this->db->update('galeri',$params);
    }
    
    /*
     * function to delete galeri
     */
    function delete_galeri($id_galeri)
    {
        $this->db->delete('galeri',array('id_galeri'=>$id_galeri));
        return;
    }
    function ambil_data($perpage, $offset){
        $this->db->order_by('id_galeri', 'desc');
        return $this->db->get("galeri", $perpage, $offset)->result();
        
    }
}
