<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konfirmasi_p_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pemesanan by id_pemesanan
     */
    function get_konfirmasi_p($id_konfirmasi)
    {
        return $this->db->get_where('konfirmasi_p',array('id_konfirmasi'=>$id_konfirmasi))->row();
    }
    
    function get_count()
    {
        return $this->db->count_all('konfirmasi_p');
    }
    /*
     * Get all pemesanan
     */
    function get_all_konfirmasi_p()
    {
        $this->db->order_by('id_konfirmasi', 'asc');
        return $this->db->get('konfirmasi_p')->result();
    }
        
    /*
     * function to add new pemesanan
     */
    function add_konfirmasi_p($params)
    {
        $this->db->insert('konfirmasi_p',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pemesanan
     */
    function update_konfirmasi_p($id_konfirmasi,$params)
    {
        $this->db->where('id_konfirmasi',$id_konfirmasi);
        return $this->db->update('konfirmasi_p',$params);
    }

    function cek_invoice($invoice)
    {
        return $this->db->get_where('konfirmasi_p',array('invoice'=>$invoice))->result();
    }
    
    /*
     * function to delete pemesanan
     */
    function delete_konfirmasi_p($id_konfirmasi)
    {
        return $this->db->delete('konfirmasi_p',array('id_konfirmasi'=>$id_konfirmasi));
    }
    
    function ambil_data($perpage, $offset, $bulan, $tahun){
      $this->db->order_by('id_konfirmasi', 'DESC');
      $this->db->where('month(tgl_sekarang)',$bulan);
      $this->db->where('year(tgl_sekarang)',$tahun);
      // $this->db->where("(alamat  LIKE '%{$keyword}%')");
        return $this->db->get("konfirmasi_p", $perpage, $offset)->result();
        
    }

    function cari($keyword){
      $this->db->like('invoice', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('konfirmasi_p')->result();
    }

       function data_konfirmasi($bulan, $tahun) {

        $this->db->select('*');
        $this->db->from('konfirmasi_p');
        $this->db->where('month(tgl_sekarang)',$bulan);
        $this->db->where('year(tgl_sekarang)',$tahun);
        // $this->db->where("status = '1'");
        // $this->db->where("(alamat  LIKE '%{$keyword}%' or provinsi  LIKE '%{$keyword}%' or kabupaten  LIKE '%{$keyword}%')");
        $this->db->order_by('id_konfirmasi', 'DESC');
        
        $query = $this->db->get();
        return $query->result();
    }
}
