<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paket_wisatum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get paket_wisatum by id_paketwisata
     */
    function get_paket_wisatum($id_paketwisata)
    {
        return $this->db->get_where('paket_wisata',array('id_paketwisata'=>$id_paketwisata))->row();
    }

    function get_count()
    {
        return $this->db->count_all('paket_wisata');
    }
        
    /*
     * Get all paket_wisata
     */
    function get_all_paket_wisata()
    {
        $this->db->order_by('id_paketwisata', 'desc');
        return $this->db->get('paket_wisata')->result_array();
    }
        
    /*
     * function to add new paket_wisatum
     */
    function add_paket_wisatum($params)
    {
        $this->db->insert('paket_wisata',$params);
        return $this->db->insert_id();
    }
    // Fungsi untuk melakukan proses upload file
    function upload(){
        $config['upload_path'] = 'resources/upload/paket_wisata';
        $config['allowed_types'] = 'jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['remove_space'] = TRUE;
    
        $this->load->library('upload', $config); // Load konfigurasi uploadnya
        if($this->upload->do_upload('gambar')){ // Lakukan upload dan Cek jika proses upload berhasil
            // Jika berhasil :
            $return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
            return $return;
        }else{
            // Jika gagal :
            $return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
            return $return;
        }
        }

        function save($upload){
        $data = array(
            // 'deskripsi'=>$this->input->post('input_deskripsi'),
            'gambar' => $upload['gambar']['file_name']
            // 'ukuran_file' => $upload['file']['file_size'],
            // 'tipe_file' => $upload['file']['file_type']
        );
        
        $this->db->insert('paket_wisata', $data);
    }


    /*
     * function to update paket_wisatum
     */
    function update_paket_wisatum($id_paketwisata,$params)
    {
        $this->db->where('id_paketwisata',$id_paketwisata);
        return $this->db->update('paket_wisata',$params);
    }
    
    /*
     * function to delete paket_wisatum
     */
    function delete_paket_wisatum($id_paketwisata)
    {
        return $this->db->delete('paket_wisata',array('id_paketwisata'=>$id_paketwisata));
    }

    function ambil_data($perpage, $offset){
        $this->db->order_by('id_paketwisata', 'desc');
        return $this->db->get("paket_wisata", $perpage, $offset)->result();
        
    }
    function cari($keyword){
      $this->db->like('nama_paketwisata', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('paket_wisata')->result();
    }

   
}
