<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pemesanan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pemesanan by id_pemesanan
     */
    function get_pemesanan($id_pemesanan)
    {
        return $this->db->get_where('pemesanan',array('id_pemesanan'=>$id_pemesanan))->row();
    }

    function datainvoice($invoice)
    {
        return $this->db->get_where('pemesanan',array('invoice'=>$invoice))->row();
    }
    
    function get_count()
    {
        return $this->db->count_all('pemesanan');
    }
    /*
     * Get all pemesanan
     */
    function get_all_pemesanan()
    {
        $this->db->order_by('id_pemesanan', 'DESC');
        return $this->db->get('pemesanan')->result();
    }

    function data_laporan($bulan, $tahun, $keyword) {

        // echo $keyword;
        // die();
        $this->db->order_by('id_pemesanan', 'DESC');
        $this->db->select('*');
        $this->db->from('pemesanan');
        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        $this->db->where("(alamat  LIKE '%{$keyword}%')");
        $this->db->where("status = '1'");
        
        
        
        $query = $this->db->get();
        return $query->result();
    }

    function data_per_laporan($id, $bulan, $tahun, $keyword) {

        $this->db->order_by('id_pemesanan', 'DESC');
        $this->db->select('*');
        $this->db->from('pemesanan');
        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        $this->db->where("(alamat  LIKE '%{$keyword}%')");
        $this->db->where("status = '1'");
        $this->db->where("id_touragent =".$id);
        
        
        $query = $this->db->get();
        return $query->result();
    }

     function data_cetak($bulan, $tahun) {

        // echo $keyword;
        // die();

        $this->db->select('*');
        $this->db->from('pemesanan');
        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        // $this->db->where("(alamat  LIKE '%{$keyword}%')");
        $this->db->where("status = '1'");
        
        $this->db->order_by('tanggal_sekarang', 'DESC');
        
        $query = $this->db->get();
        return $query->result();
    }


function data_pemesanan($bulan, $tahun,$keyword) {
        $this->db->order_by('id_pemesanan', 'DESC');
        $this->db->select('*');
        $this->db->from('pemesanan');

        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        $this->db->where("(alamat  LIKE '%{$keyword}%')");
        // $this->db->where("status = '1'");
        // $this->db->where("(alamat  LIKE '%{$keyword}%' or provinsi  LIKE '%{$keyword}%' or kabupaten  LIKE '%{$keyword}%')");
        
        
        $query = $this->db->get();
        return $query->result();
        // return $this->db->get('pemesanan')->result();
    }

        
    /*
     * function to add new pemesanan
     */
    function add_pemesanan($params)
    {
        $this->db->insert('pemesanan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pemesanan
     */
    function update_pemesanan($id_pemesanan,$params)
    {
        $this->db->where('id_pemesanan',$id_pemesanan);
        return $this->db->update('pemesanan',$params);
    }
    
    /*
     * function to delete pemesanan
     */
    function delete_pemesanan($id_pemesanan)
    {
        return $this->db->delete('pemesanan',array('id_pemesanan'=>$id_pemesanan));
    }
    public function tanggal_id($tanggal){
        $tanggal2 = substr($tanggal,8,2);
        $bulan = $this->getBulan_id(substr($tanggal,5,2));
        $tahun = substr($tanggal,0,4);
        return $tanggal2.' '.$bulan.' '.$tahun;      
    }

    

    function tanggal_en($tanggal){
        $tanggal2 = substr($tanggal,3,2);
        $bulan = substr($tanggal,0,2);
        $tahun = substr($tanggal,6,4);
        return $tahun.'-'.$bulan.'-'.$tanggal2;         
    }

    function getBulan_en($bln){
        switch ($bln){
            case 1: 
                return "January";
                break;
            case 2:
                return "February";
                break;
            case 3:
                return "March";
                break;
            case 4:
                return "April";
                break;
            case 5:
                return "May";
                break;
            case 6:
                return "June";
                break;
            case 7:
                return "July";
                break;
            case 8:
                return "August";
                break;
            case 9:
                return "September";
                break;
            case 10:
                return "October";
                break;
            case 11:
                return "November";
                break;
            case 12:
                return "December";
                break;
        }
    }
    function ambil_data($perpage, $offset, $bulan, $tahun, $keyword){
        $this->db->order_by('id_pemesanan', 'DESC');
        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        $this->db->where("(alamat  LIKE '%{$keyword}%')");
        return $this->db->get("pemesanan", $perpage, $offset)->result();
        
    }

    function cek_invoice($invoice)
    {
        return $this->db->get_where('pemesanan',array('invoice'=>$invoice))->row();
    }

    function cari($keyword){
      $this->db->like('nama_pemesan', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('pemesanan')->result();
    }

    //  function laporanpaket($id_paketwisata){
    //     $this->db->select('*');
    //     $this->db->from('paket_wisata');
    //     $this->db->where('id_paketwisata',$id_paketwisata);

    //      $query = $this->db->get();
    //     return $query->result();
    // }

     function laporanpaket($id_paket){
        $this->db->select('*');
        $this->db->from('pemesanan');

        $this->db->where('nama_paket',$id_paket);
         $this->db->where("status = '1'");

         $query = $this->db->get();
        return $query->result();
    }

     function laporanfilterpaket($id_paket,$bulan,$tahun){
        $this->db->select('*');
        $this->db->from('pemesanan');

        $this->db->where('month(tanggal_sekarang)',$bulan);
        $this->db->where('year(tanggal_sekarang)',$tahun);
        $this->db->where('nama_paket',$id_paket);
        $this->db->where("status = '1'");

         $query = $this->db->get();
        return $query->result();
    }

     function laporanpemesan($id_paket){
        $this->db->select('*');
        $this->db->from('pemesanan');

        $this->db->where('nama_pemesan',$id_paket);
         $this->db->where("status = '1'");

         $query = $this->db->get();
        return $query->result();
    }

    function rupiah($angka){
    
    $hasil_rupiah = "Rp " . number_format($angka,2,',','.');
    return $hasil_rupiah;
 
}
}
