<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penginapan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get penginapan by id_penginapan
     */
    function get_penginapan($id_penginapan)
    {
        return $this->db->get_where('penginapan',array('id_penginapan'=>$id_penginapan))->row();
    }
        

    /*
     * Get all penginapan
     */
    function get_all_penginapan()
    {
        $this->db->order_by('id_penginapan', 'desc');
        return $this->db->get('penginapan')->result_array();
    }
        
    /*
     * function to add new penginapan
     */
    function add_penginapan($params)
    {
        $this->db->insert('penginapan',$params);
        return $this->db->insert_id();
    }
    
    function upload(){
        $config['upload_path'] = 'resources/upload/penginapan/';
        $config['allowed_types'] = 'jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['remove_space'] = TRUE;
    
        $this->load->library('upload', $config); // Load konfigurasi uploadnya
        if($this->upload->do_upload('gambar')){ // Lakukan upload dan Cek jika proses upload berhasil
            // Jika berhasil :
            $return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
            return $return;
        }else{
            // Jika gagal :
            $return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
            return $return;
        }
        }

        function save($upload){
        $data = array(
            // 'deskripsi'=>$this->input->post('input_deskripsi'),
            'gambar' => $upload['gambar']['file_name']
            // 'ukuran_file' => $upload['file']['file_size'],
            // 'tipe_file' => $upload['file']['file_type']
        );
        
        $this->db->insert('penginapan', $data);
    }
    /*
     * function to update penginapan
     */
    function update_penginapan($id_penginapan,$params)
    {
        $this->db->where('id_penginapan',$id_penginapan);
        return $this->db->update('penginapan',$params);
    }
    
    /*
     * function to delete penginapan
     */
    function delete_penginapan($id_penginapan)
    {
        return $this->db->delete('penginapan',array('id_penginapan'=>$id_penginapan));
    }
     function cari($keyword){
      $this->db->like('nama_penginapan', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('penginapan')->result();
    }

    function caripenginapan($keyword){
      $this->db->like('alamat', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('penginapan')->result();
    }

    function ambil_data($perpage, $offset){
        $this->db->order_by('id_penginapan', 'desc');
        return $this->db->get("penginapan", $perpage, $offset)->result();
        
    }
}
