<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Restaurant_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get restaurant by id_restaurant
     */
    function get_restaurant($id_restaurant)
    {
        return $this->db->get_where('restaurant',array('id_restaurant'=>$id_restaurant))->row();
    }
        
    /*
     * Get all restaurant
     */
    function get_all_restaurant()
    {
        $this->db->order_by('id_restaurant', 'desc');
        return $this->db->get('restaurant')->result_array();
    }
        
    /*
     * function to add new restaurant
     */
    function add_restaurant($params)
    {
        $this->db->insert('restaurant',$params);
        return $this->db->insert_id();
    }
    
     function upload(){
        $config['upload_path'] = 'resources/upload/restaurant/';
        $config['allowed_types'] = 'jpg|png|jpeg';
        $config['max_size'] = '2048';
        $config['remove_space'] = TRUE;
    
        $this->load->library('upload', $config); // Load konfigurasi uploadnya
        if($this->upload->do_upload('gambar')){ // Lakukan upload dan Cek jika proses upload berhasil
            // Jika berhasil :
            $return = array('result' => 'success', 'file' => $this->upload->data(), 'error' => '');
            return $return;
        }else{
            // Jika gagal :
            $return = array('result' => 'failed', 'file' => '', 'error' => $this->upload->display_errors());
            return $return;
        }
        }

        function save($upload){
        $data = array(
            // 'deskripsi'=>$this->input->post('input_deskripsi'),
            'gambar' => $upload['gambar']['file_name']
            // 'ukuran_file' => $upload['file']['file_size'],
            // 'tipe_file' => $upload['file']['file_type']
        );
        
        $this->db->insert('restaurant', $data);
    }
    /*
     * function to update restaurant
     */
    function update_restaurant($id_restaurant,$params)
    {
        $this->db->where('id_restaurant',$id_restaurant);
        return $this->db->update('restaurant',$params);
    }
    
    /*
     * function to delete restaurant
     */
    function delete_restaurant($id_restaurant)
    {
        return $this->db->delete('restaurant',array('id_restaurant'=>$id_restaurant));
    }

    function cari($keyword){
      $this->db->like('nama_restaurant', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('restaurant')->result();
    }
    function ambil_data($perpage, $offset){
        $this->db->order_by('id_restaurant', 'desc');
        return $this->db->get("restaurant", $perpage, $offset)->result();
        
    }
}
