<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pemesanan by id_pemesanan
     */
    function get_sk($id_sk)
    {
        return $this->db->get_where('sk',array('id_sk'=>$id_sk))->row();
    }
    
    function get_count()
    {
        return $this->db->count_all('sk');
    }
    /*
     * Get all pemesanan
     */
    function get_all_sk()
    {
        $this->db->order_by('id_sk', 'DESC');
        return $this->db->get('sk')->result();
    }
        
    /*
     * function to add new pemesanan
     */
    function add_sk($params)
    {
        $this->db->insert('sk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pemesanan
     */
    function update_sk($id_sk,$params)
    {
        $this->db->where('id_sk',$id_sk);
        return $this->db->update('sk',$params);
    }
    
    /*
     * function to delete pemesanan
     */
    function delete_sk($id_sk)
    {
        return $this->db->delete('sk',array('id_sk'=>$id_sk));
    }
    function ambil_data($perpage, $offset){
        $this->db->order_by('id_sk', 'desc');
        return $this->db->get("sk", $perpage, $offset)->result();
        
    }

    
}
