<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tour_agent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tour_agent by id_touragent
     */
    function get_tour_agent($id_touragent)
    {
        return $this->db->get_where('tour_agent',array('id_touragent'=>$id_touragent))->row();
    }
        
    /*
     * Get all tour_agent
     */
    function get_all_tour_agent()
    {
        $this->db->order_by('id_touragent', 'desc');
        return $this->db->get('tour_agent')->result();
    }
        
    /*
     * function to add new tour_agent
     */
    function add_tour_agent($params)
    {
        $this->db->insert('tour_agent',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tour_agent
     */
    function update_tour_agent($id_touragent,$params)
    {
        $this->db->where('id_touragent',$id_touragent);
        return $this->db->update('tour_agent',$params);
    }
    
    /*
     * function to delete tour_agent
     */
    function delete_tour_agent($id_touragent)
    {
        return $this->db->delete('tour_agent',array('id_touragent'=>$id_touragent));
    }
    function cari($keyword){
      $this->db->like('nama_touragent', $keyword); //mencari data yang serupa dengan keyword
      return $this->db->get('tour_agent')->result();
    }

    function ambil_data($perpage, $offset){
        $this->db->order_by('id_touragent', 'desc');
        return $this->db->get("tour_agent", $perpage, $offset)->result();
        
    }
}
