<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('pemesanan_tourguide_model');
        $this->load->model('pemesanan_model');

        if(!$this->session->userdata('nama')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        }
        
    }

    function index()
    {
        
        // $query = $this->db->query('select * from pemesanan');
        // $total = $query->num_rows();
        

        $data['ppaket'] = $this->db->get('pemesanan')->num_rows();
        $data['pguide'] = $this->db->get('pemesanan_tourguide')->num_rows();
        $data['kpaket'] = $this->db->get('konfirmasi_p')->num_rows();
        $data['kguide'] = $this->db->get('konfirmasi_t')->num_rows();
    	
        $data['_view'] = 'layouts/admin/dashboard';
        $this->load->view('layouts/admin/main',$data);
    }
}
