<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Galeri extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Galeri_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of galeri
     */
    function index($offset=0)
    {

        $galeri = $this->db->get("galeri");


        $config['total_rows']=$galeri->num_rows();
        $config['base_url']= base_url().'admin/Galeri/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Galeri_model->ambil_data($config['per_page'], $offset);
        $data['galeri'] = $this->Galeri_model->get_all_galeri();
        
        $data['_view'] = "layouts/admin/galeri/index";
        $this->load->view('layouts/admin/main', $data);
    }

    /*
     * Adding a new galeri
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params['nama'] = $this->input->post('nama');

            if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }

            $galeri = $this->Galeri_model->add_galeri($params);
            redirect('admin/galeri');
        }
        else
        {            
            $data['_view'] = 'layouts/admin/galeri/add';
            $this->load->view('layouts/admin/main',$data);
        }
    }

    function upload_foto(){
        $set_name   = "gambar-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }







    /*
     * Editing a galeri
     */
    function edit($id_galeri)
    {   
        // check if the galeri exists before trying to edit it
        $data['galeri'] = $this->Galeri_model->get_galeri($id_galeri);
        
        if(isset($data['galeri']->id_galeri))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params->nama = $this->input->post('nama');

                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params->gambar = $foto_name;
                }

                $this->Galeri_model->update_galeri($id_galeri,$params);            
                redirect('admin/galeri');
            }
            else
            {
                $data['_view'] = 'layouts/admin/galeri/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The galeri you are trying to edit does not exist.');
    } 

    /*
     * Deleting galeri
     */
    function remove($id_galeri)
    {
        $galeri = $this->Galeri_model->get_galeri($id_galeri);

        // check if the galeri exists before trying to delete it
        if(isset($galeri->id_galeri))
        {
            $this->Galeri_model->delete_galeri($id_galeri);
            redirect('admin/galeri');
        }
        else
            show_error('The galeri you are trying to delete does not exist.');
    }

    function hapusgambar($id)
    {
        $galeri = $this->Galeri_model->get_galeri($id);

        // check if the penginapan produk exists before trying to delete it
        if(isset($galeri->id_galeri))
        {
            unlink('resources/upload/'.$galeri->gambar);
            $data['gambar'] = "";
            $this->Galeri_model->update_galeri($galeri->id_galeri,$data);
            redirect('admin/galeri/edit/'.$id);
        }
        else
          show_error('Data Penginapan tidak ada');
    }
    
}
