<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konfirmasi_t extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Konfirmasi_t_model');
        $this->load->model('Pemesanan_tourguide_model');
         $this->load->model('Tour_guide_model');
        
        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    }

    function index($offset=0)
    {

        $config['per_page']= 5;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $total_data = $this->Konfirmasi_t_model->data_konfirmasi($data['bulan'],$data['tahun'],$data['alamat']);



        $config['total_rows'] = count($total_data);
        $config['base_url']= base_url().'admin/Konfirmasi_t/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $data['konfirmasi'] = $this->Konfirmasi_t_model->data_konfirmasi($data['bulan'],$data['tahun'],$data['alamat']);

        $data['data']=$this->Konfirmasi_t_model->ambil_data($config['per_page'], $offset, $data['bulan'],$data['tahun'],$data['alamat']);
        // $konfirmasi_t = $this->db->get("konfirmasi_t");
        // $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        // $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        // $data['data'] = $this->Konfirmasi_t_model->data_konfirmasi($data['bulan'],$data['tahun']);
        // $data['konfirmasi_t'] = $this->Konfirmasi_t_model->get_all_konfirmasi_t();
        $data['_view'] = 'layouts/admin/konfirmasi_t/index';
        $this->load->view('layouts/admin/main',$data);
    }
     function validasi($id_konfirmasi)
    {   
        // check if the tour_guide exists before trying to edit it
        $data['konfirmasi_t'] = $this->Konfirmasi_t_model->get_konfirmasi_t($id_konfirmasi);
        
        if(isset($data['konfirmasi_t']->id_konfirmasi))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   

                $validasi = $this->input->post('konfirm');
                if($validasi == '1')
                {
                $data_konfirmasi = $data['konfirmasi_t'];
                $params['konfirm'] = $this->input->post('konfirm');
                $datapemesanan['status'] = 1;
                $datainvoice = $this->Pemesanan_tourguide_model->datainvoice($data_konfirmasi->invoice);
                $this->Pemesanan_tourguide_model->update_pemesanan_tourguide($datainvoice->id_pemesananguide,$datapemesanan);
                $data_pemesanan = $this->Pemesanan_tourguide_model->cek_invoice($data_konfirmasi->invoice);
                $data_guide = $this->Tour_guide_model->get_tour_guide($data_pemesanan->id_tourguide);
                $this->load->library('email');
                $config['charset'] = 'utf-8';
                $config['useragent'] = 'Hilmi';
                $config['protocol'] = 'smtp';
                $config['mailtype'] = 'html';
                $config['smtp_host'] = 'ssl://smtp.gmail.com';
                $config['smtp_port'] = '465';
                $config['smtp_timeout'] = '5';
                $config['smtp_user'] = 'genpibwi@gmail.com'; //isi dengan email gmail
                $config['smtp_pass'] = 'banyuwangi123'; //isi dengan password
                $config['crlf'] = "\r\n";
                $config['newline'] = "\r\n";
                $config['wordwrap'] = TRUE;
                $this->email->initialize($config);
                $alamat = $this->input->post('alamat');
                $email = $this->input->post('email');
                $no_telp = $this->input->post('no_telp');
                $tanggal_pemesanan = $this->input->post('tanggal_pemesanan');
                $this->email->from('genpibwi@gmail.com', "Genpi Banyuwangi");
                $this->email->to($data_pemesanan->email,$data_pemesanan->nama_pemesan);
                $this->email->subject('Konfirmasi Pembayaran Tour Guide Sukses');
                $this->email->message(
                '
                 <html>
 <head>
<style type="text/css">
     #memo {
      padding-top: 10px;
      margin: 0 140px 0 140px;
      border-bottom: 1px solid #ddd;
      height: 115px;
    }
    #memo .logo {
      float: left;
      margin-right: 20px;
    }
    #memo .logo img {
      width: 150px;
      height: 100px;
    }
    #memo .company-info {
      float: right;
      text-align: right;
    }
    #memo .company-info > div:first-child {
      line-height: 1em;
      font-weight: bold;
      font-size: 22px;
      color: #B32C39;
    }
    #memo .company-info span {
      font-size: 11px;
      display: inline-block;
      min-width: 20px;
    }
    #memo:after {
      content: "";
      display: block;
      clear: both;
    }
    #items {
      margin: 0px 0px 0px 0px;
    }
    #items .first-cell, #items table th:first-child, #items table td:first-child {
      width: 20px !important;
      padding-left: 0 !important;
      padding-right: 0 !important;
      text-align: center;
    }
    #items table {
      border-collapse: separate;
      width: 100%;
    }
    #items table th {
      font-weight: bold;
      padding: 5px 8px;
      text-align: center;
      background: #B32C39;
      color: white;
      text-transform: uppercase;
    }
    #items table th:nth-child(2) {
      width: 40%;
      text-align: center;
    }
    #items table th:last-child {
      text-align: center;
    }
    #items table td {
      padding: 9px 8px;
      text-align: center;
      border-bottom: 1px solid #ddd;
    }
    #items table td:nth-child(2) {
      text-align: center;
    }
     #invoice-info {
      float: left;
      margin: 50px 40px 0 0px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #invoice-title-number {
      font-weight: bold;
      margin: 10px 0;
      margin-left: 0px;
    }
    #invoice-title-number span {
      line-height: 0.88em;
      display: inline-block;
      min-width: 20px;
    }
    #invoice-title-number #title {
      text-transform: uppercase;
      padding: 0px 2px 0px 30px;
      font-size: 30px;
      background: #F4846F;
      color: white;
      margin-left: 0px;
      margin-bottom: 0px;
    }
    #invoice-title-number #number {
      margin-left: 10px;
      font-size: 30px;
      position: relative;
      top: 0px;
    }
    #invoice-info {
      float: left;
      margin: 50px 40px 20px 90px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #client-info {
      float: left;
      margin-left: 0px;
      min-width: 220px;
    }
    #client-info > div {
      margin-bottom: 3px;
      min-width: 20px;
    }
    #client-info span {
      display: block;
      min-width: 20px;
    }
    #client-info > span {
      text-transform: uppercase;
    }
    </style>
    </head>
<body style="background-color:#F5F5F5;">

 <section id="memo">
        <h1 align="center" style="margin-bottom:2px">GenPI Banyuwangi</h1>
    <p align="center" style="margin:0px">Dinas Kebudayaan dan Pariwisata Kabupaten Banyuwangi | Jl. Jendral A. Yani No. 78 Banyuwangi 68416</p>
    <p align="center" style="margin-top:4px"><strong>Telp: (0333) 424172 | Email: Genpibwi@gmail.com</strong></p>

      </section>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

<tr>

<td align="center">

 

<table width="660px" border="0" cellspacing="0" cellpadding="0">

<tr>

<td>
<section id="invoice-title-number">
      
        <span id="title">INVOICE</span>
        <span id="number">'.$data_konfirmasi->invoice.'</span>
        
</section>
<section id="client-info">
        <div>
          <span class="bold">'.$data_pemesanan->nama_pemesan.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->alamat.'</span>
        </div>
        
        
        <div>
          <span>'.$data_pemesanan->no_telp.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->email.'</span>
        </div>
        <p> Selamat pemesanan tour guide Anda pada tanggal '.$data_pemesanan->tanggal_sekarang.' dengan detail tour guide di bawah ini berhasil dikonfirmasi dan dinyatakan valid.</p>
      </section><br>

                     
<section id="items">
        
              <table cellpadding="0" cellspacing="0">
              
                <tr>
                  <th width="20%">Tanggal Trip</th> 
                  <th>Tour Guide</th>
                  
                  <th>Total</th>
                </tr>
                
                <tr >
                  <td>'.$data_pemesanan->tanggal_pemesanan.'</td>
                  <td>'.$data_guide->nama_tourguide.'</td>
           
                  <td> '.'Rp. '.number_format($data_guide->harga, 2,',','.').'</td>
                </tr>
                
              </table>
              
            </section><br><br>

                        <a href="'. site_url('admin/konfirmasi_t/cetak/'.$data_pemesanan->id_pemesananguide.'') .'">Cetak PDF</a>.

                        Untuk info lebih lanjut, silahkan hubungi Customer Service.
                        <table border="0" style="width: 30%" style="background-color:#FFD700;">
                        <tr><th style="text-align:left">Riska</th><th>: 085791261912</th></tr>
                        <tr><th style="text-align:left">Arif</th><th>: 082143110959</th></tr>
                        </table>
                         <br>


                        </p>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" >

                        <tr>

                        <td>

                       <div class="footer">
    <p align="center"><a href style="color: #94c045">GenPI Banyuwangi</a> | Copyright 2018</p>
  </div>

                        <p><small></small></p>
                        </table>
 

</body>

</html>
                     
                        '
                );

                    if ($this->email->send())
                    {
                      $this->Konfirmasi_t_model->update_konfirmasi_t($id_konfirmasi,$params); 
                      redirect('admin/konfirmasi_t/index');
                    }
                }
                else if ($validasi == '2') 
                {

                $data_konfirmasi = $data['konfirmasi_t'];

                $params['konfirm'] = $this->input->post('konfirm');
                $datapemesanan['status'] = 2;
                $datainvoice = $this->Pemesanan_tourguide_model->datainvoice($data_konfirmasi->invoice);
                $this->Pemesanan_tourguide_model->update_pemesanan_tourguide($datainvoice->id_pemesananguide,$datapemesanan); 




                // $data_konfirmasi = $data['konfirmasi_t'];
                // $params['konfirm'] = $this->input->post('konfirm');
                // $data_konfirmasi->konfirm = 2;
                $data_pemesanan = $this->Pemesanan_tourguide_model->cek_invoice($data_konfirmasi->invoice);
                $data_guide = $this->Tour_guide_model->get_tour_guide($data_pemesanan->id_tourguide);

                $this->load->library('email');

                $config['charset'] = 'utf-8';
                $config['useragent'] = 'Hilmi';
                $config['protocol'] = 'smtp';
                $config['mailtype'] = 'html';
                $config['smtp_host'] = 'ssl://smtp.gmail.com';
                $config['smtp_port'] = '465';
                $config['smtp_timeout'] = '5';
                $config['smtp_user'] = 'genpibwi@gmail.com'; //isi dengan email gmail
                $config['smtp_pass'] = 'banyuwangi123'; //isi dengan password
                $config['crlf'] = "\r\n";
                $config['newline'] = "\r\n";
                $config['wordwrap'] = TRUE;
                $this->email->initialize($config);
               
                $this->email->from('genpibwi@gmail.com', "Genpi Banyuwangi");
                $this->email->to($data_pemesanan->email,$data_pemesanan->nama_pemesan);
                $this->email->subject('Konfirmasi Pembayaran Tour Guide Gagal');
                $this->email->message(
                '

                <html>
 <head>
<style type="text/css">
     #memo {
      padding-top: 10px;
      margin: 0 140px 0 140px;
      border-bottom: 1px solid #ddd;
      height: 115px;
    }
    #memo .logo {
      float: left;
      margin-right: 20px;
    }
    #memo .logo img {
      width: 150px;
      height: 100px;
    }
    #memo .company-info {
      float: right;
      text-align: right;
    }
    #memo .company-info > div:first-child {
      line-height: 1em;
      font-weight: bold;
      font-size: 22px;
      color: #B32C39;
    }
    #memo .company-info span {
      font-size: 11px;
      display: inline-block;
      min-width: 20px;
    }
    #memo:after {
      content: "";
      display: block;
      clear: both;
    }
    #items {
      margin: 0px 0px 0px 0px;
    }
    #items .first-cell, #items table th:first-child, #items table td:first-child {
      width: 20px !important;
      padding-left: 0 !important;
      padding-right: 0 !important;
      text-align: center;
    }
    #items table {
      border-collapse: separate;
      width: 100%;
    }
    #items table th {
      font-weight: bold;
      padding: 5px 8px;
      text-align: center;
      background: #B32C39;
      color: white;
      text-transform: uppercase;
    }
    #items table th:nth-child(2) {
      width: 40%;
      text-align: center;
    }
    #items table th:last-child {
      text-align: center;
    }
    #items table td {
      padding: 9px 8px;
      text-align: center;
      border-bottom: 1px solid #ddd;
    }
    #items table td:nth-child(2) {
      text-align: center;
    }
     #invoice-info {
      float: left;
      margin: 50px 40px 0 0px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #invoice-title-number {
      font-weight: bold;
      margin: 10px 0;
      margin-left: 0px;
    }
    #invoice-title-number span {
      line-height: 0.88em;
      display: inline-block;
      min-width: 20px;
    }
    #invoice-title-number #title {
      text-transform: uppercase;
      padding: 0px 2px 0px 30px;
      font-size: 30px;
      background: #F4846F;
      color: white;
      margin-left: 0px;
      margin-bottom: 0px;
    }
    #invoice-title-number #number {
      margin-left: 10px;
      font-size: 30px;
      position: relative;
      top: 0px;
    }
    #invoice-info {
      float: left;
      margin: 50px 40px 20px 90px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #client-info {
      float: left;
      margin-left: 0px;
      min-width: 220px;
    }
    #client-info > div {
      margin-bottom: 3px;
      min-width: 20px;
    }
    #client-info span {
      display: block;
      min-width: 20px;
    }
    #client-info > span {
      text-transform: uppercase;
    }
    </style>
    </head>
<body style="background-color:#F5F5F5;">

 <section id="memo">
        <h1 align="center" style="margin-bottom:2px">GenPI Banyuwangi</h1>
    <p align="center" style="margin:0px">Dinas Kebudayaan dan Pariwisata Kabupaten Banyuwangi | Jl. Jendral A. Yani No. 78 Banyuwangi 68416</p>
    <p align="center" style="margin-top:4px"><strong>Telp: (0333) 424172 | Email: Genpibwi@gmail.com</strong></p>

      </section>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

<tr>

<td align="center">

 

<table width="660px" border="0" cellspacing="0" cellpadding="0">

<tr>

<td>
<section id="invoice-title-number">
      
        <span id="title">INVOICE</span>
        <span id="number">'.$data_konfirmasi->invoice.'</span>
        
</section>
<section id="client-info">
        <div>
          <span class="bold">'.$data_pemesanan->nama_pemesan.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->alamat.'</span>
        </div>
        
        
        <div>
          <span>'.$data_pemesanan->no_telp.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->email.'</span>
        </div>
        <p>
                       Konfirmasi pembayaran yang Anda lakukan dinyatakan TIDAK VALID. Silahkan cek lagi Syarat & Ketentuan dari paket wisata yang dipesan atau cek lagi rincian pemesanan yang telah dikirimkan ke email sebelumnya kemudian lakukan konfirmasi pembayaran ulang <a href="'. site_url('Konfirmasi') .'">disini</a>.</p>
      </section><br>

                     


                        Untuk info lebih lanjut, silahkan hubungi Customer Service.
                        <table border="0" style="width: 30%" style="background-color:#FFD700;">
                        <tr><th style="text-align:left">Riska</th><th>: 085791261912</th></tr>
                        <tr><th style="text-align:left">Arif</th><th>: 082143110959</th></tr>
                        </table>
                         <br>


                        </p>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" >

                        <tr>

                        <td>

                       <div class="footer">
    <p align="center"><a href style="color: #94c045">GenPI Banyuwangi</a> | Copyright 2018</p>
  </div>

                        <p><small></small></p>
                        </table>
 

</body>

</html>                    
                     
                        '
                );

                    if ($this->email->send())
                    {
                      $this->Konfirmasi_t_model->update_konfirmasi_t($id_konfirmasi,$params); 
                      redirect('admin/konfirmasi_t/index');
                    }
                }


            }
            else
            {
                $data['show'] = $this->Konfirmasi_t_model->get_konfirmasi_t($id_konfirmasi);
                $data['cekpesan'] = $this->Pemesanan_tourguide_model->datainvoice($data['konfirmasi_t']->invoice);
                $data['konfirm'] = '';
                $data['_view'] = 'layouts/admin/konfirmasi_t/validasi';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The tour_guide you are trying to edit does not exist.');
    } 

    function show($id_konfirmasi)
    {
        $data['show'] = $this->Konfirmasi_t_model->get_konfirmasi_t($id_konfirmasi);
        $data['_view'] = 'layouts/admin/konfirmasi_t/show';
        $this->load->view('layouts/admin/main',$data);
    } 

     function cetak($id_pemesananguide)
    {
        $data['show'] = $this->Pemesanan_tourguide_model->get_pemesanan_tourguide($id_pemesananguide);
        $data['guide'] = $this->Tour_guide_model->get_tour_guide($data['show']->id_tourguide);

        echo $data['show']->id_pemesananguide;
        // die();
        $this->load->view('pdf/bukti_pt',$data);

        // $html = $this->output->get_output();

        // Convert to PDF
        // $this->dompdf->load_html($html);
        // $this->dompdf->render();
        //utk menampilkan preview pdf
        // $this->dompdf->stream("cetak-bukti.pdf", array('Attachment' => 0));
    }

     function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['konfirmasi_t'] = $this->Konfirmasi_t_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    // $data['cekpesan'] = $this->Pemesanan_model->datainvoice($data['konfirmasi_p']->invoice);
    $data['_view'] = 'layouts/admin/konfirmasi_t/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }

}
