<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Konfirmasi_p extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Konfirmasi_p_model');
        $this->load->model('Pemesanan_model');
        $this->load->model('Paket_wisatum_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
         
    }

    function index($offset=0)
    {
     //    $konfirmasi_p = $this->db->get("konfirmasi_p");

     //    $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
     //    $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
     //    // $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat');
     //    $data['data'] = $this->Konfirmasi_p_model->data_konfirmasi($data['bulan'],$data['tahun']);
    	// $data['konfirmasi_p'] = $this->Konfirmasi_p_model->get_all_konfirmasi_p();

        $config['per_page']= 5;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $total_data = $this->Konfirmasi_p_model->data_konfirmasi($data['bulan'],$data['tahun'],$data['alamat']);



        $config['total_rows'] = count($total_data);
        $config['base_url']= base_url().'admin/Konfirmasi_p/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $data['konfirmasi'] = $this->Konfirmasi_p_model->data_konfirmasi($data['bulan'],$data['tahun'],$data['alamat']);

        $data['data']=$this->Konfirmasi_p_model->ambil_data($config['per_page'], $offset, $data['bulan'],$data['tahun'],$data['alamat']);

        $data['_view'] = 'layouts/admin/konfirmasi_p/index';
        $this->load->view('layouts/admin/main',$data);
    }

     function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params['tgl_sekarang'] = $this->input->post('tgl_sekarang');
            $params['invoice'] = $this->input->post('invoice');
            $params['nama_pemesan'] = $this->input->post('nama');
            $params['jumlah_transfer'] = $this->input->post('jumlah');             
                if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
            $konfirmasi_p_id = $this->Konfirmasi_p_model->add_konfirmasi_p($params);
            redirect('admin/konfirmasi_p/index');
        }
        else
        {            
            $data['_view'] = 'layouts/admin/konfirmasi_p/add';
            $this->load->view('layouts/admin/main',$data);
        }
    } 

    function upload_foto(){
        $set_name   = "gambar-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/bukti_pembayaran/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }

    function validasi($id_konfirmasi)
    {   
        // check if the tour_guide exists before trying to edit it
        $data['konfirmasi_p'] = $this->Konfirmasi_p_model->get_konfirmasi_p($id_konfirmasi);
        // $data['konfirmasi_p'] = $this->Konfirmasi_p_model->get_konfirmasi_p($id_konfirmasi);
        if(isset($data['konfirmasi_p']->id_konfirmasi))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {  
                $validasi = $this->input->post('konfirm');
                if($validasi == '1')
                {
                $data_konfirmasi = $data['konfirmasi_p'];

                $params['konfirm'] = $this->input->post('konfirm');
                $datapemesanan['status'] = 1;
                $datainvoice = $this->Pemesanan_model->datainvoice($data_konfirmasi->invoice);
                $this->Pemesanan_model->update_pemesanan($datainvoice->id_pemesanan,$datapemesanan); 


              
                $data_pemesanan = $this->Pemesanan_model->cek_invoice($data_konfirmasi->invoice);
                $data_paket = $this->Paket_wisatum_model->get_paket_wisatum($data_pemesanan->nama_paket);

                

                $this->load->library('email');

                $config['charset'] = 'utf-8';
                $config['useragent'] = 'Hilmi';
                $config['protocol'] = 'smtp';
                $config['mailtype'] = 'html';
                $config['smtp_host'] = 'ssl://smtp.gmail.com';
                $config['smtp_port'] = '465';
                $config['smtp_timeout'] = '5';
                $config['smtp_user'] = 'genpibwi@gmail.com'; //isi dengan email gmail
                $config['smtp_pass'] = 'banyuwangi123'; //isi dengan password
                $config['crlf'] = "\r\n";
                $config['newline'] = "\r\n";
                $config['wordwrap'] = TRUE;
                $this->email->initialize($config);
               
              
                $alamat = $this->input->post('alamat');
                $email = $this->input->post('email');
                $no_telp = $this->input->post('no_telp');
                $jumlah_anggota = $this->input->post('jumlah_anggota');
                $tanggal_pemesanan = $this->input->post('tanggal_pemesanan');

                $this->email->from('genpibwi@gmail.com', "Genpi Banyuwangi");
                $this->email->to($data_pemesanan->email,$data_pemesanan->nama_pemesan);
                $this->email->subject('Konfirmasi Pembayaran Paket Wisata Sukses');
                $this->email->message(
                '
 <html>
 <head>
<style type="text/css">
     #memo {
      padding-top: 10px;
      margin: 0 140px 0 140px;
      border-bottom: 1px solid #ddd;
      height: 115px;
    }
    #memo .logo {
      float: left;
      margin-right: 20px;
    }
    #memo .logo img {
      width: 150px;
      height: 100px;
    }
    #memo .company-info {
      float: right;
      text-align: right;
    }
    #memo .company-info > div:first-child {
      line-height: 1em;
      font-weight: bold;
      font-size: 22px;
      color: #B32C39;
    }
    #memo .company-info span {
      font-size: 11px;
      display: inline-block;
      min-width: 20px;
    }
    #memo:after {
      content: "";
      display: block;
      clear: both;
    }
    #items {
      margin: 0px 0px 0px 0px;
    }
    #items .first-cell, #items table th:first-child, #items table td:first-child {
      width: 20px !important;
      padding-left: 0 !important;
      padding-right: 0 !important;
      text-align: center;
    }
    #items table {
      border-collapse: separate;
      width: 100%;
    }
    #items table th {
      font-weight: bold;
      padding: 5px 8px;
      text-align: center;
      background: #B32C39;
      color: white;
      text-transform: uppercase;
    }
    #items table th:nth-child(2) {
      width: 40%;
      text-align: center;
    }
    #items table th:last-child {
      text-align: center;
    }
    #items table td {
      padding: 9px 8px;
      text-align: center;
      border-bottom: 1px solid #ddd;
    }
    #items table td:nth-child(2) {
      text-align: center;
    }
     #invoice-info {
      float: left;
      margin: 50px 40px 0 0px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #invoice-title-number {
      font-weight: bold;
      margin: 10px 0;
      margin-left: 0px;
    }
    #invoice-title-number span {
      line-height: 0.88em;
      display: inline-block;
      min-width: 20px;
    }
    #invoice-title-number #title {
      text-transform: uppercase;
      padding: 0px 2px 0px 30px;
      font-size: 30px;
      background: #F4846F;
      color: white;
      margin-left: 0px;
      margin-bottom: 0px;
    }
    #invoice-title-number #number {
      margin-left: 10px;
      font-size: 30px;
      position: relative;
      top: 0px;
    }
    #invoice-info {
      float: left;
      margin: 50px 40px 20px 90px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #client-info {
      float: left;
      margin-left: 0px;
      min-width: 220px;
    }
    #client-info > div {
      margin-bottom: 3px;
      min-width: 20px;
    }
    #client-info span {
      display: block;
      min-width: 20px;
    }
    #client-info > span {
      text-transform: uppercase;
    }
    </style>
    </head>
<body style="background-color:#F5F5F5;">

 <section id="memo">
        <h1 align="center" style="margin-bottom:2px">GenPI Banyuwangi</h1>
    <p align="center" style="margin:0px">Dinas Kebudayaan dan Pariwisata Kabupaten Banyuwangi | Jl. Jendral A. Yani No. 78 Banyuwangi 68416</p>
    <p align="center" style="margin-top:4px"><strong>Telp: (0333) 424172 | Email: Genpibwi@gmail.com</strong></p>

      </section>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

<tr>

<td align="center">

 

<table width="660px" border="0" cellspacing="0" cellpadding="0">

<tr>

<td>
<section id="invoice-title-number">
      
        <span id="title">INVOICE</span>
        <span id="number">'.$data_konfirmasi->invoice.'</span>
        
</section>
<section id="client-info">
        <div>
          <span class="bold">'.$data_pemesanan->nama_pemesan.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->alamat.'</span>
        </div>
        
        
        <div>
          <span>'.$data_pemesanan->no_telp.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->email.'</span>
        </div>
        <p> Selamat pemesanan paket wisata Anda pada tanggal '.$data_pemesanan->tanggal_sekarang.' dengan detail paket wisata di bawah ini berhasil dikonfirmasi dan dinyatakan valid.</p>
      </section><br>

                     
<section id="items">
        
              <table cellpadding="0" cellspacing="0">
              
                <tr>
                  <th width="20%">Tanggal Trip</th> 
                  <th>Paket Wisata</th>
                  <th>Qty</th>
                  <th>Total</th>
                </tr>
                
                <tr >
                  <td>'.$data_pemesanan->tanggal_pemesanan.'</td>
                  <td>'.$data_paket->nama_paketwisata.'</td>
                  <td>'.$data_pemesanan->jumlah_anggota.' pax</td>
                  <td> '.'Rp. '.number_format($data_paket->harga*$data_pemesanan->jumlah_anggota, 2,',','.').'</td>
                </tr>
                
              </table>
              
            </section><br><br>

                        <a href="'. site_url('admin/konfirmasi_p/cetak/'.$data_pemesanan->id_pemesanan.'') .'">Cetak PDF</a>.

                        Untuk info lebih lanjut, silahkan hubungi Customer Service.
                        <table border="0" style="width: 30%" style="background-color:#FFD700;">
                        <tr><th style="text-align:left">Riska</th><th>: 085791261912</th></tr>
                        <tr><th style="text-align:left">Arif</th><th>: 082143110959</th></tr>
                        </table>
                         <br>


                        </p>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" >

                        <tr>

                        <td>

                       <div class="footer">
    <p align="center"><a href style="color: #94c045">GenPI Banyuwangi</a> | Copyright 2018</p>
  </div>

                        <p><small></small></p>
                        </table>
 

</body>

</html>
                     
                        '
                );

                if ($this->email->send())
                {
                  $this->Konfirmasi_p_model->update_konfirmasi_p($id_konfirmasi,$params); 
                  redirect('admin/konfirmasi_p/index');
                }
                }
                else if($validasi == '2')
                {

                $data_konfirmasi = $data['konfirmasi_p'];
                $params['konfirm'] = $this->input->post('konfirm');
                $datapemesanan['status'] = 2;
                // $data_konfirmasi->konfirm = 2;
                 $datainvoice = $this->Pemesanan_model->datainvoice($data_konfirmasi->invoice);
                $this->Pemesanan_model->update_pemesanan($datainvoice->id_pemesanan,$datapemesanan); 



                $data_pemesanan = $this->Pemesanan_model->cek_invoice($data_konfirmasi->invoice);
                $data_paket = $this->Paket_wisatum_model->get_paket_wisatum($data_pemesanan->nama_paket);

                $this->load->library('email');

                $config['charset'] = 'utf-8';
                $config['useragent'] = 'Hilmi';
                $config['protocol'] = 'smtp';
                $config['mailtype'] = 'html';
                $config['smtp_host'] = 'ssl://smtp.gmail.com';
                $config['smtp_port'] = '465';
                $config['smtp_timeout'] = '5';
                $config['smtp_user'] = 'genpibwi@gmail.com'; //isi dengan email gmail
                $config['smtp_pass'] = 'banyuwangi123'; //isi dengan password
                $config['crlf'] = "\r\n";
                $config['newline'] = "\r\n";
                $config['wordwrap'] = TRUE;
                $this->email->initialize($config);
               
                $this->email->from('genpibwi@gmail.com', "Genpi Banyuwangi");
                $this->email->to($data_pemesanan->email,$data_pemesanan->nama_pemesan);
                $this->email->subject('Konfirmasi Pembayaran Paket Wisata Gagal');
                $this->email->message(
                '

 <html>
 <head>
<style type="text/css">
     #memo {
      padding-top: 10px;
      margin: 0 140px 0 140px;
      border-bottom: 1px solid #ddd;
      height: 115px;
    }
    #memo .logo {
      float: left;
      margin-right: 20px;
    }
    #memo .logo img {
      width: 150px;
      height: 100px;
    }
    #memo .company-info {
      float: right;
      text-align: right;
    }
    #memo .company-info > div:first-child {
      line-height: 1em;
      font-weight: bold;
      font-size: 22px;
      color: #B32C39;
    }
    #memo .company-info span {
      font-size: 11px;
      display: inline-block;
      min-width: 20px;
    }
    #memo:after {
      content: "";
      display: block;
      clear: both;
    }
    #items {
      margin: 0px 0px 0px 0px;
    }
    #items .first-cell, #items table th:first-child, #items table td:first-child {
      width: 20px !important;
      padding-left: 0 !important;
      padding-right: 0 !important;
      text-align: center;
    }
    #items table {
      border-collapse: separate;
      width: 100%;
    }
    #items table th {
      font-weight: bold;
      padding: 5px 8px;
      text-align: center;
      background: #B32C39;
      color: white;
      text-transform: uppercase;
    }
    #items table th:nth-child(2) {
      width: 40%;
      text-align: center;
    }
    #items table th:last-child {
      text-align: center;
    }
    #items table td {
      padding: 9px 8px;
      text-align: center;
      border-bottom: 1px solid #ddd;
    }
    #items table td:nth-child(2) {
      text-align: center;
    }
     #invoice-info {
      float: left;
      margin: 50px 40px 0 0px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #invoice-title-number {
      font-weight: bold;
      margin: 10px 0;
      margin-left: 0px;
    }
    #invoice-title-number span {
      line-height: 0.88em;
      display: inline-block;
      min-width: 20px;
    }
    #invoice-title-number #title {
      text-transform: uppercase;
      padding: 0px 2px 0px 30px;
      font-size: 30px;
      background: #F4846F;
      color: white;
      margin-left: 0px;
      margin-bottom: 0px;
    }
    #invoice-title-number #number {
      margin-left: 10px;
      font-size: 30px;
      position: relative;
      top: 0px;
    }
    #invoice-info {
      float: left;
      margin: 50px 40px 20px 90px;
    }
    #invoice-info > div > span {
      display: inline-block;
      min-width: 20px;
      min-height: 18px;
      margin-bottom: 3px;
    }
    #invoice-info > div > span:first-child {
      color: black;
    }
    #invoice-info > div > span:last-child {
      color: #aaa;
    }
    #invoice-info:after {
      content: "";
      display: block;
      clear: both;
    }
    #client-info {
      float: left;
      margin-left: 0px;
      min-width: 220px;
    }
    #client-info > div {
      margin-bottom: 3px;
      min-width: 20px;
    }
    #client-info span {
      display: block;
      min-width: 20px;
    }
    #client-info > span {
      text-transform: uppercase;
    }
    </style>
    </head>
<body style="background-color:#F5F5F5;">

 <section id="memo">
        <h1 align="center" style="margin-bottom:2px">GenPI Banyuwangi</h1>
    <p align="center" style="margin:0px">Dinas Kebudayaan dan Pariwisata Kabupaten Banyuwangi | Jl. Jendral A. Yani No. 78 Banyuwangi 68416</p>
    <p align="center" style="margin-top:4px"><strong>Telp: (0333) 424172 | Email: Genpibwi@gmail.com</strong></p>

      </section>

<table width="100%" border="0" cellspacing="0" cellpadding="0">

<tr>

<td align="center">

 

<table width="660px" border="0" cellspacing="0" cellpadding="0">

<tr>

<td>
<section id="invoice-title-number">
      
        <span id="title">INVOICE</span>
        <span id="number">'.$data_konfirmasi->invoice.'</span>
        
</section>
<section id="client-info">
        <div>
          <span class="bold">'.$data_pemesanan->nama_pemesan.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->alamat.'</span>
        </div>
        
        
        <div>
          <span>'.$data_pemesanan->no_telp.'</span>
        </div>
        
        <div>
          <span>'.$data_pemesanan->email.'</span>
        </div>
       <p>
                       Konfirmasi pembayaran yang Anda lakukan dinyatakan TIDAK VALID. Silahkan cek lagi Syarat & Ketentuan dari paket wisata yang dipesan atau cek lagi rincian pemesanan yang telah dikirimkan ke email sebelumnya kemudian lakukan konfirmasi pembayaran ulang <a href="'. site_url('Konfirmasi') .'">disini</a>.</p>

      </section><br>

                     


                        Untuk info lebih lanjut, silahkan hubungi Customer Service.
                        <table border="0" style="width: 30%" style="background-color:#FFD700;">
                        <tr><th style="text-align:left">Riska</th><th>: 085791261912</th></tr>
                        <tr><th style="text-align:left">Arif</th><th>: 082143110959</th></tr>
                        </table>
                         <br>


                        </p>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" >

                        <tr>

                        <td>

                       <div class="footer">
    <p align="center"><a href style="color: #94c045">GenPI Banyuwangi</a> | Copyright 2018</p>
  </div>

                        <p><small></small></p>
                        </table>
 

</body>

</html>


                      
                     
                        '
                );

                if ($this->email->send())
                {
                  $this->Konfirmasi_p_model->update_konfirmasi_p($id_konfirmasi,$params); 
                  redirect('admin/konfirmasi_p/index');
                }
                }

            }
            else
            {

                
                


                // echo $data['konfirmasi_p']->invoice;

                $data['show'] = $this->Konfirmasi_p_model->get_konfirmasi_p($id_konfirmasi);
                $data['cekpesan'] = $this->Pemesanan_model->datainvoice($data['konfirmasi_p']->invoice);
                 $data['paket'] = $this->Paket_wisatum_model->get_paket_wisatum($data['cekpesan']->nama_paket);

                
                $data['konfirm'] = '';
                $data['_view'] = 'layouts/admin/konfirmasi_p/validasi';
                $this->load->view('layouts/admin/main',$data);

            }
        }
        else
            show_error('The tour_guide you are trying to edit does not exist.');
    } 

     function show($id_konfirmasi)
    {
        $data['show'] = $this->Konfirmasi_p_model->get_konfirmasi_p($id_konfirmasi);
        $data['_view'] = 'layouts/admin/konfirmasi_p/show';
        $this->load->view('layouts/admin/main',$data);
    }

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['konfirmasi_p'] = $this->Konfirmasi_p_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    // $data['cekpesan'] = $this->Pemesanan_model->datainvoice($data['konfirmasi_p']->invoice);
    $data['_view'] = 'layouts/admin/konfirmasi_p/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }

     function cetak($id_pemesanan)
    {
        $data['show'] = $this->Pemesanan_model->get_pemesanan($id_pemesanan);
        $data['paket'] = $this->Paket_wisatum_model->get_paket_wisatum($data['show']->nama_paket);

        echo $data['show']->id_pemesanan;
        // die();
        $this->load->view('pdf/bukti_pp',$data);

        // $html = $this->output->get_output();

        // Convert to PDF
        // $this->dompdf->load_html($html);
        // $this->dompdf->render();
        //utk menampilkan preview pdf
        // $this->dompdf->stream("cetak-bukti.pdf", array('Attachment' => 0));
    }
 
}
