<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paket_wisatum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Paket_wisatum_model');
        $this->load->model('Tour_agent_model');
        $this->load->library('pagination');
        $this->load->helper('url');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin Tour Agent.');
            redirect('login');
        }
    } 

    /*
     * Listing of paket_wisata
     */
    function index($offset=0)
    {
        $paket_wisatum = $this->db->get("paket_wisata");


        $config['total_rows']=$paket_wisatum->num_rows();
        $config['base_url']= base_url().'admin/Paket_wisatum/index';
        $config['per_page']= 10;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Paket_wisatum_model->ambil_data($config['per_page'], $offset);


        $this->db->select('*');
        $this->db->from('paket_wisata');
        $this->db->join('tour_agent', 'tour_agent.id_touragent = paket_wisata.id_touragent');


        $data['paket_wisata'] = $this->db->get()->result_array();
        
        $data['_view'] = 'layouts/admin/paket_wisatum/index';
        $this->load->view('layouts/admin/main',$data);
    }

    /*
     * Adding a new paket_wisatum
     */




    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['paket_wisata'] = $this->Paket_wisatum_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/paket_wisatum/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }
   
    function add()
    {   
        
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params['nama_paketwisata'] = $this->input->post('nama_paketwisata');
            $params['fasilitas'] = $this->input->post('fasilitas');
            $params['harga'] = $this->input->post('harga');
            if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
             $params['id_touragent'] = $this->input->post('id_touragent');
             $params['jadwal'] = $this->input->post('jadwal');
             $params['sk'] = $this->input->post('sk');
            $paket_wisatum_id = $this->Paket_wisatum_model->add_paket_wisatum($params);
            redirect('admin/paket_wisatum');
        }
        else
        {        
            $data['tour_agent']  = $this->Tour_agent_model->get_all_tour_agent(); 
            $data['_view'] = 'layouts/admin/paket_wisatum/add';
            $this->load->view('layouts/admin/main',$data);
        }
    }  
    function upload_foto(){
        $set_name   = "gambar-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/paket_wisata/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }





    /*
     * Editing a paket_wisatum
     */
    function edit($id_paketwisata)
    {   
        // check if the paket_wisatum exists before trying to edit it
        $data['paket_wisatum'] = $this->Paket_wisatum_model->get_paket_wisatum($id_paketwisata);
        
        if(isset($data['paket_wisatum']->id_paketwisata))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params->nama_paketwisata = $this->input->post('nama_paketwisata');
                $params->fasilitas = $this->input->post('fasilitas');
                $params->harga = $this->input->post('harga');
                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params->gambar = $foto_name;
                }
                $params->id_touragent = $this->input->post('id_touragent');
                $params->jadwal = $this->input->post('jadwal');
                $params->sk = $this->input->post('sk');

                $this->Paket_wisatum_model->update_paket_wisatum($id_paketwisata,$params);            
                redirect('admin/paket_wisatum/index');
            }
            else
            {
                $data['tour_agent']  = $this->Tour_agent_model->get_all_tour_agent(); 
                $data['_view'] = 'layouts/admin/paket_wisatum/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The paket_wisatum you are trying to edit does not exist.');
    } 

    /*
     * Deleting paket_wisatum
     */
    function remove($id_paketwisata)
    {
        $paket_wisatum = $this->Paket_wisatum_model->get_paket_wisatum($id_paketwisata);

        // check if the paket_wisatum exists before trying to delete it
        if(isset($paket_wisatum->id_paketwisata))
        {
            $this->Paket_wisatum_model->delete_paket_wisatum($id_paketwisata);
            redirect('admin/paket_wisatum/index');
        }
        else
            show_error('The paket_wisatum you are trying to delete does not exist.');
    }

    function hapusgambar($id)
    {
        $paket_wisatum = $this->Paket_wisatum_model->get_paket_wisatum($id);

        // check if the penginapan produk exists before trying to delete it
        if(isset($paket_wisatum->id_paketwisata))
        {
            unlink('resources/upload/paket_wisata/'.$paket_wisatum->gambar);
            $data['gambar'] = "";
            $this->Paket_wisatum_model->update_paket_wisatum($paket_wisatum->id_paketwisata,$data);
            redirect('admin/paket_wisatum/edit/'.$id);
        }
        else
          show_error('Data Penginapan tidak ada');
    }
    
}
