<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pemesanan_guide extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pemesanan_tourguide_model');
        $this->load->model('Tour_guide_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin Tour Guide.');
            redirect('login');
        }
    } 

    /*
     * Listing of pemesanan
     */
    // function index()
    // {
    function index($offset=0)
    {
        // $p_guide = $this->db->get("pemesanan_tourguide");
        // $this->db->select('*');
        // $this->db->from('pemesanan_tourguide');
        // $this->db->join('tour_guide', 'tour_guide.id_tourguide = pemesanan_tourguide.id_tourguide');
        // $data['pemesanan_tourguide'] = $this->db->get()->result_array();

        // $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        // $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        // $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        // $data['data'] = $this->Pemesanan_tourguide_model->data_pemesanan($data['bulan'],$data['tahun'],$data['alamat']);
        // $data['pemesanan'] = $this->Pemesanan_tourguide_model->get_all_pemesanan_tourguide(); 


        // $data['data']=$this->Pemesanan_tourguide_model->ambil_data($config['per_page'], $offset);
        

        $config['per_page']= 5;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $total_data = $this->Pemesanan_tourguide_model->data_pemesanan($data['bulan'],$data['tahun'],$data['alamat']);



        $config['total_rows'] = count($total_data);
        $config['base_url']= base_url().'admin/Pemesanan_guide/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;
        $data['bulan'] = $this->input->post('bulan') ? $this->input->post('bulan') : date("m");
        $data['tahun'] = $this->input->post('tahun') ? $this->input->post('tahun') : date("Y");
        $data['alamat'] = $this->input->post('alamat') ? $this->input->post('alamat') : "";
        $data['pemesanan'] = $this->Pemesanan_tourguide_model->data_pemesanan($data['bulan'],$data['tahun'],$data['alamat']);

        $data['data']=$this->Pemesanan_tourguide_model->ambil_data($config['per_page'], $offset, $data['bulan'],$data['tahun'],$data['alamat']);
        $data['_view'] = 'layouts/admin/pemesanan_guide/index';
        $this->load->view('layouts/admin/main',$data);
    }

    /*
     * Adding a new pemesanan
     */

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['pemesanan'] = $this->Pemesanan_tourguide_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/pemesanan_guide/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }

    function add()
    {   
        $cekkuota = $this->Pemesanan_tourguide_model->kuota($id_tourguide, $tgl_sekarang);
        if(isset($_POST) && count($_POST) > 0)     
        {   
            if(count($cekkuota) >= 2){
                die($cekkuota);
                $params = array(
                'nama_pemesan' => $this->input->post('nama_pemesan'),
                'alamat' => $this->input->post('alamat'),
                'email' => $this->input->post('email'),
                'no_telp' => $this->input->post('no_telp'),
                'tanggal_pemesanan' => $this->Pemesanan_tourguide_model->tanggal_en($this->input->post('tanggal_pemesanan')),
                
                );
                
                $pemesananguide_id = $this->Pemesanan_tourguide_model->add_pemesanan_tourguide($params);
                redirect('admin/pemesanan_guide/index');
            } else {
                die("tes");
            }
        }
        else
        {            
            $data['_view'] = 'layouts/admin/pemesanan_guide/add';
            $this->load->view('layouts/admin/main',$data);
        }

    } 

    /*
     * Editing a pemesanan
     */
    function edit($id_pemesananguide)
    {   
        // check if the pemesanan exists before trying to edit it
        $data['pemesanan_tourguide'] = $this->Pemesanan_tourguide_model->get_pemesanan_tourguide($id_pemesananguide);
        
        if(isset($data['pemesanan_tourguide']->id_pemesananguide))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_pemesan' => $this->input->post('nama_pemesan'),
                'nama_paket' => $this->input->post('nama_paket'),
                'alamat' => $this->input->post('alamat'),
                'email' => $this->input->post('email'),
                'no_telp' => $this->input->post('no_telp'),
                'jumlah_anggota' => $this->input->post('jumlah_anggota'),
                'tanggal_pemesanan' => $this->input->post('tanggal_pemesanan'),
                );

                $this->Pemesanan_tourguide_model->update_pemesanan($id_pemesananguide,$params);            
                redirect('admin/pemesanan_guide/index');
            }
            else
            {
                $data['_view'] = 'layouts/admin/pemesanan_guide/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The pemesanan you are trying to edit does not exist.');
    } 

    function show($id_pemesananguide)
    {
        $data['show'] = $this->Pemesanan_tourguide_model->get_pemesanan_tourguide($id_pemesananguide);
        $data['_view'] = 'layouts/admin/pemesanan_guide/show';
        $this->load->view('layouts/admin/main',$data);
    }
    /*
     * Deleting pemesanan
     */
    function remove($id_pemesananguide)
    {
        $pemesananguide = $this->Pemesanan_tourguide_model->get_pemesanan_tourguide($id_pemesananguide);

        // check if the pemesanan exists before trying to delete it
        if(isset($pemesananguide->id_pemesananguide))
        {
            $this->Pemesanan_tourguide_model->delete_pemesanan_tourguide($id_pemesananguide);
            redirect('admin/pemesanan_guide/index');
        }
        else
            show_error('The pemesanan you are trying to delete does not exist.');
    }
    // 
    
}
