<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penginapan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Penginapan_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of penginapan
     */
    function index($offset=0)
    {

        $penginapan = $this->db->get("penginapan");


        $config['total_rows']=$penginapan->num_rows();
        $config['base_url']= base_url().'admin/Penginapan/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_closen']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Penginapan_model->ambil_data($config['per_page'],$offset);

        $this->db->select('*');
        $this->db->from('penginapan');
         $data['penginapan'] = $this->db->get()->result_array();
        
        $data['_view'] = 'layouts/admin/penginapan/index';
        $this->load->view('layouts/admin/main',$data);
    }

    
    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['penginapan'] = $this->Penginapan_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/penginapan/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }
    /*
     * Adding a new penginapan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params['nama_penginapan'] = $this->input->post('nama_penginapan');
            $params['alamat'] = $this->input->post('alamat');
            $params['kelas'] = $this->input->post('kelas');
            if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
            
            $penginapan_id = $this->Penginapan_model->add_penginapan($params);
            redirect('admin/penginapan/index');
        }
        else
        {            
            $data['_view'] = 'layouts/admin/penginapan/add';
            $this->load->view('layouts/admin/main',$data);
        }
    }

    function upload_foto(){
        $set_name   = "gambar-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/penginapan/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }

    /*
     * Editing a penginapan
     */
    function edit($id_penginapan)
    {   
        // check if the penginapan exists before trying to edit it
        $data['penginapan'] = $this->Penginapan_model->get_penginapan($id_penginapan);
        
        if(isset($data['penginapan']->id_penginapan))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params->nama_penginapan = $this->input->post('nama_penginapan');
                $params->alamat = $this->input->post('alamat');
                $params->kelas = $this->input->post('kelas');
                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params->gambar = $foto_name;
                }

                $this->Penginapan_model->update_penginapan($id_penginapan,$params);            
                redirect('admin/penginapan/index');
            }
            else
            {
                $data['_view'] = 'layouts/admin/penginapan/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The penginapan you are trying to edit does not exist.');
    } 

    /*
     * Deleting penginapan
     */
    function remove($id_penginapan)
    {
        $penginapan = $this->Penginapan_model->get_penginapan($id_penginapan);

        // check if the penginapan exists before trying to delete it
        if(isset($penginapan->id_penginapan))
        {
            unlink('resources/upload/penginapan/'.$penginapan->gambar);
            $this->Penginapan_model->delete_penginapan($id_penginapan);
            redirect('admin/penginapan/index');
        }
        else
            show_error('The penginapan you are trying to delete does not exist.');
    }

    function hapusgambar($id)
    {
        $penginapan = $this->Penginapan_model->get_penginapan($id);

        // check if the penginapan produk exists before trying to delete it
        if(isset($penginapan->id_penginapan))
        {
            unlink('resources/upload/penginapan/'.$penginapan->gambar);
            $data['gambar'] = "";
            $this->Penginapan_model->update_penginapan($penginapan->id_penginapan,$data);
            redirect('admin/penginapan/edit/'.$id);
        }
        else
          show_error('Data Penginapan tidak ada');
    }
    
}
