<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Restaurant extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restaurant_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of restaurant
     */
    function index($offset=0)
    {
         $restaurant = $this->db->get("restaurant");


        $config['total_rows']=$restaurant->num_rows();
        $config['base_url']= base_url().'admin/Restaurant/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Restaurant_model->ambil_data($config['per_page'], $offset);

        $data['restaurant'] = $this->Restaurant_model->get_all_restaurant();
        
        $data['_view'] = 'layouts/admin/restaurant/index';
        $this->load->view('layouts/admin/main',$data);
    }

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['restaurant'] = $this->Restaurant_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/restaurant/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }

    /*
     * Adding a new restaurant
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params['nama_restaurant'] = $this->input->post('nama_restaurant');
            $params['alamat'] = $this->input->post('alamat');
            $params['no_telp'] = $this->input->post('no_telp');
            if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
            
            $restaurant_id = $this->Restaurant_model->add_restaurant($params);
            redirect('admin/restaurant/index');
        }
        else
        {            
            $data['_view'] = 'layouts/admin/restaurant/add';
            $this->load->view('layouts/admin/main',$data);
        }
    }

     function upload_foto(){
        $set_name   = "gambar-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/restaurant/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }

    /*
     * Editing a restaurant
     */
    function edit($id_restaurant)
    {   
        // check if the restaurant exists before trying to edit it
        $data['restaurant'] = $this->Restaurant_model->get_restaurant($id_restaurant);
        
        if(isset($data['restaurant']->id_restaurant))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                    $params->nama_restaurant = $this->input->post('nama_restaurant');
                    $params->alamat = $this->input->post('alamat');
                    $params->no_telp = $this->input->post('no_telp');
                    if (!empty($_FILES['gambar']['name'])) {
                        $foto_name    = $this->upload_foto();
                        $params->gambar = $foto_name;
                    }

                $this->Restaurant_model->update_restaurant($id_restaurant,$params);            
                redirect('admin/restaurant/index');
            }
            else
            {
                $data['_view'] = 'layouts/admin/restaurant/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The restaurant you are trying to edit does not exist.');
    } 

    /*
     * Deleting restaurant
     */
    function remove($id_restaurant)
    {
        $restaurant = $this->Restaurant_model->get_restaurant($id_restaurant);

        // check if the restaurant exists before trying to delete it
        if(isset($restaurant->id_restaurant))
        {
            $this->Restaurant_model->delete_restaurant($id_restaurant);
            redirect('admin/restaurant/index');
        }
        else
            show_error('The restaurant you are trying to delete does not exist.');
    }

     function hapusgambar($id)
    {
        $restaurant = $this->Restaurant_model->get_restaurant($id);

        // check if the penginapan produk exists before trying to delete it
        if(isset($restaurant->id_restaurant))
        {
            unlink('resources/upload/restaurant/'.$restaurant->gambar);
            $data['gambar'] = "";
            $this->Restaurant_model->update_restaurant($restaurant->id_restaurant,$data);
            redirect('admin/restaurant/edit/'.$id);
        }
        else
          show_error('Data Penginapan tidak ada');
    }
    
}
