<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sk_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of galeri
     */
    function index($offset=0)
    {

        $sk = $this->db->get("sk");


        $config['total_rows']=$sk->num_rows();
        $config['base_url']= base_url().'admin/Sk/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Sk_model->ambil_data($config['per_page'], $offset);
        $data['sk'] = $this->Sk_model->get_all_sk();
        
        $data['_view'] = "layouts/admin/sk/index";
        $this->load->view('layouts/admin/main', $data);
    }

    /*
     * Adding a new galeri
     */
    
}
