<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tour_guide extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tour_guide_model');
        $this->load->model('Pemesanan_tourguide_model');
        $this->load->model('User_model');


        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of tour_guide
     */
    function index($offset=0)
    {

         $guide = $this->db->get("tour_guide");


        $config['total_rows']=$guide->num_rows();
        $config['base_url']= base_url().'admin/Tour_guide/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Tour_guide_model->ambil_data($config['per_page'], $offset);
        $this->db->select('*');
        $this->db->from('tour_guide');
         $data['tour_guide'] = $this->db->get()->result_array();
        
        
        $data['_view'] = 'layouts/admin/tour_guide/index';
        $this->load->view('layouts/admin/main',$data);
    }

    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['tour_guide'] = $this->Tour_guide_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/tour_guide/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }

    /*
     * Adding a new tour_guide
     */
    function add()
    {   
        
        if(isset($_POST) && count($_POST) > 0)     
        {   
            // $this->load->library('form_validatian');
            $username = $this->input->post('username');
            $cekuser = $this->User_model->tambahuser($username);
            // echo count($cekuser);
            // die();
            if(count($cekuser) >= 1){
             echo '<script type="text/javascript">alert("Username sudah digunakan");window.location.replace("'.base_url('Admin/Tour_guide/add').'")</script>';

            // redirect('Admin/Tour_guide/add');
            } 
            else 
            {
            $namaguide = $this->input->post('nama_tourguide');
            // $fotoguide = $this->input->post('gambar');

            $params['nama_tourguide'] = $this->input->post('nama_tourguide');
            $params['tanggal_lahir'] = $this->input->post('tanggal_lahir');
            $params['alamat'] = $this->input->post('alamat');
            $params['no_telp'] = $this->input->post('no_telp');
            $params['bahasa'] = $this->input->post('bahasa');
            if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
            $params['harga'] = $this->input->post('harga');
            $params['status'] = $this->input->post('status');

            $tour_guide_id = $this->Tour_guide_model->add_tour_guide($params);

            $data['nama'] = $namaguide;
            $data['gambar'] = $foto_name;
            $data['username'] = $this->input->post('username');
            $data['password'] = md5($this->input->post('password'));
            $data['level'] = "tourguide";
            $data['id_tourguide'] = $this->db->insert_id();

            $user_id =  $this->User_model->add_user($data);
            
            
            redirect('admin/tour_guide/index');
        }
        
    }
    else
        {            
             $data['status'] = '';
            $data['_view'] = 'layouts/admin/tour_guide/add';
            $this->load->view('layouts/admin/main',$data);
        }
    }  

    function upload_foto(){
        $set_name   = "Tour_guide-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/user/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }


    /*
     * Editing a tour_guide
     */
    function edit($id_tourguide)
    {   
        // check if the tour_guide exists before trying to edit it
        $data['tour_guide'] = $this->Tour_guide_model->get_tour_guide($id_tourguide);
        
        if(isset($data['tour_guide']->id_tourguide))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params->nama_tourguide = $this->input->post('nama_tourguide');
                $params->tanggal_lahir = $this->input->post('tanggal_lahir');
                $params->alamat = $this->input->post('alamat');
                $params->no_telp = $this->input->post('no_telp');
                $params->bahasa = $this->input->post('bahasa');
                if (!empty($_FILES['gambar']['name'])) {
                    $foto_name    = $this->upload_foto();
                    $params->gambar = $foto_name;
                }
                $params->harga = $this->input->post('harga');
                $params->status = $this->input->post('status');

                $this->Tour_guide_model->update_tour_guide($id_tourguide,$params);            
                redirect('admin/tour_guide/index');
            }
            else
            {
                $data['status'] = '';
                $data['_view'] = 'layouts/admin/tour_guide/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The tour_guide you are trying to edit does not exist.');
    } 

    /*
     * Deleting tour_guide
     */
    function remove($id_tourguide)
    {
        $tour_guide = $this->Tour_guide_model->get_tour_guide($id_tourguide);

        // check if the tour_guide exists before trying to delete it
        if(isset($tour_guide->id_tourguide))
        {
            $this->Tour_guide_model->delete_tour_guide($id_tourguide);
            redirect('admin/tour_guide/index');
        }
        else
            show_error('The tour_guide you are trying to delete does not exist.');
    }
    
}
