<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tour_agent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tour_agent_model');
        $this->load->model('User_model');


        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of tour_agent
     */
    function index($offset=0)
    {
         $agent = $this->db->get("tour_agent");


        $config['total_rows']=$agent->num_rows();
        $config['base_url']= base_url().'admin/Tour_agent/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->Tour_agent_model->ambil_data($config['per_page'], $offset);

        $data['tour_agent'] = $this->Tour_agent_model->get_all_tour_agent();
        
        $data['_view'] = 'layouts/admin/tour_agent/index';
        $this->load->view('layouts/admin/main',$data);
    }
    function cari(){

    $keyword = $this->input->get('cari', TRUE); //mengambil nilai dari form input cari
    $data['tour_agent'] = $this->Tour_agent_model->cari($keyword); //mencari data karyawan berdasarkan inputan
    $data['_view'] = 'layouts/admin/tour_agent/cari';
    $this->load->view('layouts/admin/main', $data); //menampilkan data yang sudah dicari
    }
    /*
     * Adding a new tour_agent
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $username = $this->input->post('username');
            $cekuser = $this->User_model->tambahuser($username);
            // echo count($cekuser);
            // die();
            if(count($cekuser) >= 1){
          
            echo '<script type="text/javascript">alert("Username sudah digunakan");window.location.replace("'.base_url('Admin/Tour_agent/add').'")</script>';
            // redirect('Admin/Tour_agent/add');
            } 
            else 
            {

            $namaagent = $this->input->post('nama_touragent');
            // $fotoagent = $this->input->post('gambar');

            $params['nama_touragent'] = $this->input->post('nama_touragent');
			$params['email'] = $this->input->post('email');
			$params['alamat'] = $this->input->post('alamat');
			$params['no_telp'] = $this->input->post('no_telp');
             if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;

            }
            $tour_agent_id = $this->Tour_agent_model->add_tour_agent($params);

            $data['nama'] = $namaagent;
            $data['gambar'] = $foto_name;
            $data['username'] = $this->input->post('username');
            $data['password'] = md5($this->input->post('password'));
            $data['level'] = 'touragent';
            $data['id_touragent'] = $this->db->insert_id();
            $user_id =  $this->User_model->add_user($data);
            
            
            redirect('admin/tour_agent/index');
            }
        
        } 
        else
        {            
            $data['_view'] = 'layouts/admin/tour_agent/add';
            $this->load->view('layouts/admin/main',$data);
        }
}

     function upload_foto(){
        $set_name   = "Touragent-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/user/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }  

     function edit($id_touragent)
    {   
        // check if the paket_wisatum exists before trying to edit it
        $data['tour_agent'] = $this->Tour_agent_model->get_tour_agent($id_touragent);
        
        if(isset($data['tour_agent']->id_touragent))
        {

            if(isset($_POST) && count($_POST) > 0)     
            {   
                
                $params->nama_touragent = $this->input->post('nama_touragent');
                $params->email = $this->input->post('email');
                $params->alamat = $this->input->post('alamat');
                $params->no_telp = $this->input->post('no_telp');

                $data->username = $this->input->post('username');

                $this->User_model->update_user($id_user,$data);

                $this->Tour_agent_model->update_tour_agent($id_touragent,$params);            
                redirect('admin/tour_agent/index');
            }
            else
            {
                $data['_view'] = 'layouts/admin/tour_agent/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The paket_wisatum you are trying to edit does not exist.');
    } 


    /*
     * Deleting tour_agent
     */
    function remove($id_touragent)
    {
        $tour_agent = $this->Tour_agent_model->get_tour_agent($id_touragent);

        // check if the tour_agent exists before trying to delete it
        if(isset($tour_agent->id_touragent))
        {
            $this->Tour_agent_model->delete_tour_agent($id_touragent);
            redirect('admin/tour_agent/index');
        }
        else
            show_error('The tour_agent you are trying to delete does not exist.');
    }
    
}
