<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');

        if(!$this->session->userdata('level')){
            $this->session->set_flashdata('login_gagal', 'Anda Harus Login terlebih dahulu.');
            redirect('login');
        } else if($this->session->userdata('level') && ($this->session->userdata('level') == "touragent" || $this->session->userdata('level') == "tourguide")){
             $this->session->set_flashdata('login_gagal', 'Halaman Ini hanya dapat diakses oleh admin.');
            redirect('login');
        }
    } 

    /*
     * Listing of user
     */
    function index($offset=0)
    {
        $user = $this->db->get("user");


        $config['total_rows']=$user->num_rows();
        $config['base_url']= base_url().'admin/User/index';
        $config['per_page']= 5;


        $config['full_tag_open']="<ul class='pagination pagination-sm' style='position:relative; top: -25px'> ";
        $config['full_tag_close']="</ul>";
        $config['num_tag_open']="<li>";
        $config['num_tag_close']="</li>";
        $config['cur_tag_open']="<li class='disabled'><li class='active'><a href='#'>";
        $config['cur_tag_close']="<span class='sr-only'></span></a></li>";
        $config['next_tag_open']="<li>";
        $config['next_tag_close']="</li>";
        $config['prev_tag_open']="<li>";
        $config['prev_tag_close']="</li>";
        $config['first_tag_open']="<li>";
        $config['first_tag_close']="</li>";
        $config['last_tag_open']="<li>";
        $config['last_tag_close']="</li>";

        $this->pagination->initialize($config);
        
        $data['halaman']=$this->pagination->create_links();
        $data['offset']=$offset;

        $data['data']=$this->User_model->ambil_data($config['per_page'], $offset);

        $data['user'] = $this->User_model->get_all_user();

        // $data['user'] = $this->User_model->get_all_user();
        
        $data['_view'] = 'layouts/admin/user/index';
        $this->load->view('layouts/admin/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {
        $username = $this->input->post('username');
        $cekuser = $this->User_model->tambahuser($username);
        // echo count($cekuser);
        // die();
        if(count($cekuser) >= 1){  
           echo '<script type="text/javascript">alert("Username sudah digunakan");window.location.replace("'.base_url('admin/user/add').'")</script>';       

            // redirect('Admin/User/add');
            } 
            else 
            {

            $params['password'] = md5($this->input->post('password'));
            $params['nama'] = $this->input->post('nama');
            $params['username'] = $this->input->post('username');
            $params['level'] = $this->input->post('level');
                if (!empty($_FILES['gambar']['name'])) {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
            }
            
            
            $user_id = $this->User_model->add_user($params);
            redirect('admin/user/index');
            }
        
    }
    else
        {            
            $data['_view'] = 'layouts/admin/user/add';
            $this->load->view('layouts/admin/main',$data);
        }
}

    function upload_foto(){
        $set_name   = "Admin-".RAND(0000,9999);
        $path       = $_FILES['gambar']['name'];
        $extension  = ".".pathinfo($path, PATHINFO_EXTENSION);

        $config['upload_path']          = './resources/upload/user/';
        $config['allowed_types']        = 'gif|jpg|jpeg|png';
        $config['max_size']             = 9024;
        $config['file_name']            = "$set_name".$extension;
        $this->load->library('upload', $config);
        // proses upload
        $upload = $this->upload->do_upload('gambar');

        if ($upload == FALSE) {
            $error = array('error' => $this->upload->display_errors());
            dump($error);
            dump('Gambar gagal diupload! Periksa gambar');
        }

        $upload = $this->upload->data();

        return $upload['file_name'];
    }  

    /*
     * Editing a user
     */
    function edit($id_user)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id_user);
        
        if(isset($data['user']['id_user']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params['nama'] = $this->input->post('nama');
                $params['username'] = $this->input->post('username');
			    $params['password'] = md5($this->input->post('password'));
                $params['level'] = $this->input->post('level');
                if (!empty($_FILES['gambar']['name'])) 
                {
                $foto_name    = $this->upload_foto();
                $params['gambar'] = $foto_name;
                }
					
               

                $this->User_model->update_user($id_user,$params);            
                redirect('admin/user/index');
            }
            else
            {
                $data['_view'] = 'layouts/admin/user/edit';
                $this->load->view('layouts/admin/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id_user)
    {
        $user = $this->User_model->get_user($id_user);

        // check if the user exists before trying to delete it
        if(isset($user['id_user']))
        {
            $this->User_model->delete_user($id_user);
            redirect('admin/user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }

    function hapusgambar($id)
    {
        $user = $this->User_model->get_user($id);

        // check if the penginapan produk exists before trying to delete it
        if(isset($user->id_user))
        {
            unlink('resources/upload/user/'.$user->gambar);
            $data['gambar'] = "";
            $this->User_model->update_user($user->id_user,$data);
            redirect('admin/user/edit/'.$id);
        }
        else
          show_error('Data Penginapan tidak ada');
    }
    
}
